### ISSUE TITLE
how to use twig 2.x

### ISSUE THREAD

**Issue by bnomei** [fvsch/kirby-twig#27]
using composer to install `fvsch/kirby-twig` still does not allow one to install twig `^2.4.4`. any ideas how to upgrade?

**Comment by bnomei** [comment]
hm. nevermind. drupal is stuck to 1.25 as well so my template migration will have no issues.

**Comment by fvsch** [comment]
I’m thinking about updating to Twig 2.x in a next major release, but 2.x does not support the `Twig_Autoloader` class, and supports usage with Composer only.

So I’d have to version an entire `vendor` directory for the Zip download, or go Composer-only for this plugin (which I’d like because maintaining two different branches is a pain ^^).
